export const copy = {
  site: {
    name: 'まなスレ   ',
    tagline: '学生向けの掲示板',
    logoChar: '',
    description: '親しみやすく、安心して使える掲示板サイト。',
    footerNote: 'やさしい空気を守るための小さなルールを大切にしています。',
    copyright: '© 2026 まなスレ ',
  },
  nav: {
    home: 'ホーム',
    rules: 'ルール',
    newThread: 'スレを立てる',
  },
  home: {
    moodLabel: '今日の雰囲気',
    moods: ['まったり', 'のんびり', 'ゆるやか', '和やか', 'ほっこり '],
    headlineSuffix: '',
    subcopy: '利用ルールを守り、相手への配慮を前提に会話を進めてください。',
    emptyTitle: 'まだスレッドがありません',
    emptyDescription: '最初のスレッドを作成して、会話を開始してください。',
    emptyAction: 'スレを立てる',
  },
  search: {
    keywordLabel: 'キーワード',
    keywordPlaceholder: 'タイトルや本文から探す',
    submit: '検索',
    clear: 'クリア',
    rateLimitedTitle: '検索が早すぎます',
    rateLimitedDescription: '操作が早すぎます。少し時間をおいて再試行してください。',
  },
  categoryPage: {
    label: 'カテゴリ',
    emptyTitle: 'このカテゴリはまだ静かです',
    emptyDescription: 'このカテゴリの最初のスレッドを作成してください。',
    emptyAction: 'スレを立てる',
  },
  threadCard: {
    threadLabel: 'スレッド',
    lastPosted: '最終更新',
    replies: '返信',
    repliesUnit: '件',
  },
  pagination: {
    prev: '前へ',
    next: '次へ',
    page: 'ページ',
  },
  thread: {
    authorLabel: '投稿者',
    hiddenTitle: 'このスレッドは非表示です',
    hiddenDescription: '運営対応により表示を控えています。ご理解ありがとうございます。',
    noReplies: 'まだ返信はありません。必要に応じて返信を投稿してください。',
    replyTitle: '返信を投稿する',
    replyDescription: '内容を確認のうえ、丁寧な表現で返信してください。',
    replyCountLabel: '返信数',
    sortLabel: '並び順',
    sortOldest: '古い順',
    sortNewest: '新しい順',
  },
  post: {
    anonymous: '匿名',
    copy: 'コピー',
    copySuccess: '内容をコピーしました',
  },
  badges: {
    staff: '運営',
    pinned: '固定',
  },
  report: {
    button: '通報',
    title: '通報理由',
    close: '閉じる',
    submit: '通報する',
    submitting: '送信中…',
    placeholder: '補足メモ（任意）',
    reasons: [
      { value: 'personal', label: '個人情報が含まれている' },
      { value: 'harassment', label: '誹謗中傷・攻撃的な表現' },
      { value: 'spam', label: '宣伝・スパム' },
      { value: 'hate', label: '差別的・ヘイト表現' },
      { value: 'other', label: 'その他' },
    ],
    success: '通報を受け付けました。内容を確認します。',
    error: '通報に失敗しました',
    networkError: '通信に失敗しました。時間をおいて再試行してください。',
  },
  selfDelete: {
    button: '削除',
    deleting: '削除中...',
    threadConfirm: 'このスレを非表示（削除）にします。よろしいですか？',
    postConfirm: 'この返信を非表示（削除）にします。よろしいですか？',
    success: '削除しました。',
    error: '削除に失敗しました',
    networkError: '通信に失敗しました。時間をおいて再試行してください。',
  },
  threadForm: {
    pageLabel: 'スレッド作成',
    pageTitle: 'スレッドを作成',
    pageDescription: '利用ルールを確認し、内容を整理したうえで投稿してください。',
    titleLabel: 'タイトル',
    titlePlaceholder: '話したいテーマをひとことで',
    titleHelp: '80文字以内で入力してください。',
    bodyLabel: '本文',
    bodyPlaceholder: '今の気持ちや背景を書いてみてください',
    bodyHelp: '2000文字以内で入力してください。',
    nameLabel: '表示名（任意）',
    namePlaceholder: '未入力なら「匿名」になります',
    nameHelp: '最大 20 文字',
    guidelinesTitle: '投稿ガイドライン',
    guidelinesBody:
      '個人情報の掲載、誹謗中傷、差別表現、スパム投稿は禁止です。違反投稿は削除対象になります。',
    submit: 'スレッドを作成する',
    submitting: '投稿中…',
    success: 'スレッドを作成しました。',
    error: '投稿に失敗しました',
    networkError: '通信に失敗しました。時間をおいて再試行してください。',
  },
  postForm: {
    bodyLabel: '本文',
    bodyPlaceholder: '返信内容を入力してください',
    bodyHelp: '内容を確認し、簡潔で丁寧な表現で入力してください。',
    nameLabel: '表示名（任意）',
    namePlaceholder: '未入力なら「匿名」になります',
    nameHelp: '最大 20 文字',
    submit: '返信を送る',
    submitting: '送信中…',
    success: '返信を投稿しました。',
    error: '投稿に失敗しました',
    networkError: '通信に失敗しました。時間をおいて再試行してください。',
  },
  rules: {
    label: 'ルール',
    title: 'みんなで守る、安心の約束',
    intro:
      '誰でも安心して利用できる場を維持するため、以下のルールを必ず確認してください。',
    items: [
      '個人情報（電話番号・住所・本名など）は書かないでください。',
      '誹謗中傷・差別的表現・脅しは禁止です。違反投稿は削除対象になります。',
      '宣伝・スパム行為は控えてください。',
      '管理者が不適切と判断した投稿は、削除または非表示にする場合があります。',
    ],
    reportTitle: '通報の使い方',
    reportBody:
      '投稿右下の「通報」ボタンから理由を選ぶと、運営に通知されます。相手を責めるためではなく、安心を守るための仕組みとして使ってください。',
    reportNote: '通報内容は投稿者には公開されません。',
  },
  admin: {
    label: '運営',
    headerBadge: '管理者',
    footerLoginLabel: '管理者ログイン',
    footerAdminLink: '管理画面',
    loginTitle: '管理者ログイン',
    loginDescription:
      '管理者パスワードで認証します。試行回数が一定を超えると一時的にログインを制限します。',
    passwordLabel: '管理者パスワード',
    passwordPlaceholder: 'pass',
    loginButton: 'ログイン',
    loggingIn: 'ログイン中...',
    loginSuccess: '管理画面にログインしました。',
    loginError: '管理者ログインに失敗しました。',
    logoutButton: 'ログアウト',
    loggingOut: 'ログアウト中...',
    logoutError: 'ログアウトに失敗しました。',
    logoutSuccess: 'ログアウトしました。',
    dashboardTitle: '通報管理',
    dashboardDescription: '通報された投稿を確認し、必要に応じて非表示にします。',
    reportStatsTotal: '累計',
    reportStats24h: '24時間',
    reportStats1h: '1時間',
    currentRoleLabel: '現在の権限',
    reportListTitle: '通報一覧',
    reportListDescription: '新しい通報から順に表示しています。',
    targetLabel: '対象',
    reasonLabel: '理由',
    noteLabel: '補足',
    noNote: 'なし',
    noReports: '通報はまだありません。',
    hideButton: '非表示にする',
    hiding: '処理中...',
    hideSuccess: '対象を非表示にしました。',
    hideError: '非表示処理に失敗しました。',
    alreadyHidden: 'すでに非表示',
    permissionDeniedLabel: '閲覧専用',
    threadDeleteButton: 'スレを削除',
    threadDeleting: '削除中...',
    threadDeleteConfirm: 'このスレを非表示（論理削除）にします。よろしいですか？',
    threadDeleteSuccess: 'スレを非表示にしました。',
    threadDeleteError: 'スレの非表示に失敗しました。',
    postDeleteButton: '返信を削除',
    postDeleting: '削除中...',
    postDeleteConfirm: 'この返信を非表示（論理削除）にします。よろしいですか？',
    postDeleteSuccess: '返信を非表示にしました。',
    postDeleteError: '返信の非表示に失敗しました。',
    pinButton: '固定',
    unpinButton: '固定解除',
    pinning: '固定中...',
    unpinning: '解除中...',
    pinSuccess: '固定しました。',
    unpinSuccess: '固定を解除しました。',
    pinError: '固定に失敗しました。',
    networkError: '通信に失敗しました。少し時間を置いてください。',
  },
  error: {
    label: 'エラー',
    title: '少しだけ迷子になりました',
    description: '画面の表示に失敗しました。もう一度試すか、ホームへ戻ってください。',
    retry: 'もう一度読み込む',
    home: 'ホームへ戻る',
  },
  notFound: {
    label: '見つかりません',
    title: 'お探しのページが見つかりません',
    description: 'URLが間違っているか、ページが移動した可能性があります。',
    action: 'ホームに戻る',
  },
} as const;
